// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn21EBu5nXP1M583gix00Yj1ikf9WC48k',
    appId: '1:721694459000:web:dbb65f650a70a6ea68998d',
    messagingSenderId: '721694459000',
    projectId: 'messanger-3869a',
    authDomain: 'messanger-3869a.firebaseapp.com',
    storageBucket: 'messanger-3869a.firebasestorage.app',
    measurementId: 'G-K7CR53YNSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW6OdXoLF0-HazlxcuttxO36XOyGw7_Mc',
    appId: '1:721694459000:android:f4ad5752652b7f5068998d',
    messagingSenderId: '721694459000',
    projectId: 'messanger-3869a',
    storageBucket: 'messanger-3869a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW110GQw_sr-UUPB6sfe14XT3ihETA-IE',
    appId: '1:721694459000:ios:0fe1c8d42a98f6b068998d',
    messagingSenderId: '721694459000',
    projectId: 'messanger-3869a',
    storageBucket: 'messanger-3869a.firebasestorage.app',
    iosBundleId: 'com.example.messanger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW110GQw_sr-UUPB6sfe14XT3ihETA-IE',
    appId: '1:721694459000:ios:0fe1c8d42a98f6b068998d',
    messagingSenderId: '721694459000',
    projectId: 'messanger-3869a',
    storageBucket: 'messanger-3869a.firebasestorage.app',
    iosBundleId: 'com.example.messanger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn21EBu5nXP1M583gix00Yj1ikf9WC48k',
    appId: '1:721694459000:web:c174de2c35c3186768998d',
    messagingSenderId: '721694459000',
    projectId: 'messanger-3869a',
    authDomain: 'messanger-3869a.firebaseapp.com',
    storageBucket: 'messanger-3869a.firebasestorage.app',
    measurementId: 'G-58VVJ3Y642',
  );
}
